AudiusProject/audius-mobile-client

android/app/build.gradle
ios/AudiusReactNative.xcodeproj/project.pbxproj
ios/AudiusReactNative/Info.plist
src/components/oauth/OAuth.tsx
src/message.ts
src/store/oauth/actions.ts
src/store/oauth/reducer.ts
src/store/oauth/selectors.ts

Adds the instagram message to be checked for on handleMessage from the dapp to native layer.
Updates the oauth redux store to add a provider field to differentiate between twitter and instagram auth
Updates the OAuth component 
* it now has logic for instagram polling
* It sends an empty message back when the popup is closed -  so the client isn't stuck in the loading phase
* Handles instagram message, passing the code back on success
This was tested by running the local dapp and port forwarding to an android device.
The Instagram/Twitter popup window appeared and was able to close and send a message back. 
The actual login to twitter/instagram to retrieve the code was not tested because I was unable to set a redirect url in the dapp to be verified by server. 
Am planning on testing in …

Adds instagram verification

---

android/app/build.gradle
ios/AudiusReactNative.xcodeproj/project.pbxproj
ios/AudiusReactNative/Info.plist
ios/Podfile
ios/Podfile.lock
package-lock.json
package.json
src/App.tsx
src/components/notification-reminder/NotificationReminder.tsx
src/components/web/WebApp.tsx
src/message.ts
src/notifications.ts
src/store/lifecycle/actions.ts
src/store/lifecycle/reducer.ts
src/store/lifecycle/selectors.ts
src/utils/logging.ts
src/utils/useSessionCount.ts

https://trello.com/c/vWEe1wwb/1693-reminder-to-turn-on-notifications
Add a drawer that shows up every 10 sessions to have a user turn on notifications if they've never been turned on or explicitly disabled. Also shows on native mobile sign in flow.
New tools:
- ReactNativePermissions library (our react native push notifications doesn't have a way to handle the notification state "unset but requestable" (see Results.DENIED) in the PR)
- Session counter
- Lifecycle state for signed in
Tests

Add push notification reminder

---

src/utils/analytics.ts

Closes https://linear.app/audius/issue/AUD-298/flush-react-native-analytics-on-sign-up-flow
The only programmatic way of doing it would be to give react native awareness of all the event names/types and maybe we want to do it at some point, but i think overkill to help us in the near term

[AUD-298] Flush segment events as they come in

---

src/components/oauth/OAuth.tsx

This PR:
* Updates the url for which the TikTok oauth polling is waiting. This is so that choosing a 3rd party oauth provider like Apple or Google doesn't immediately end the oauth flow. This problem doesn't exist on desktop because the oauth providers open in a new window

Update TikTok polling to accomodate 3rd party oauth providers

---

ios/AudiusReactNative.xcodeproj/project.pbxproj
src/components/web/WebApp.tsx

Noticed this while trying to repro some of the `Network Error` stuff we see on mobile. External links are not working correctly from within the app because this regex had a .* that snuck in.
Also modifies the Excluded Architectures to only be simulator builds
Locally running app

[AUD-867] Fix external links

---

src/components/web/WebApp.tsx

I don't believe we need this, but it was added here:
https://github.com/AudiusProject/audius-mobile-client-old/commit/13cc6bbb04bbe4f0c9f41303a733cdf8155f81ee#diff-8f820c4f37cc3f8198a8145000b9d76e17d5fa1322550288d0e0a951a897892c
And i dont know why.
This currently breaks deep links to hash ids, e.g. audius.co/tracks/7eP5n

Remove tolowercase for url deep link

---

src/components/audio/Audio.tsx
src/components/audio/GoogleCast.tsx
src/message/types.ts
src/store/audio/reducer.ts
src/store/audio/selectors.ts

App used to crash when on a lineup that has only one track. We were trying to pull the genre off a non-existent track, which caused an exception.
This PR also handles triggering autoplay from native mobile when close to end of lineup.
iPhone and Android emulators

Fix autoplay app crash bug

---

android/app/build.gradle
android/build.gradle

This PR fixes the instant crash on android 11 after upgrading to `targetSdk: 30`. The better fix would be to upgrade to react-native 0.66
It also bumps the android build to trigger a new CI run. NOTE: needed to bump to 151 because of other versions that got pushed as part of the auto incrementing build number work

Set version of okhttp to fix android 11 crash

---

src/components/web/WebApp.tsx

This PR:
* Reloads the WebView when the content process is terminated on ios. This will hopefully resolve the White Screen Of Death
See: https://github.com/react-native-webview/react-native-webview/issues/2199
Test that a reload works properly. Have not been able to test that it actually resolves the issue because it can only be reproduced when waiting 12+ hours with the app in the background

[AUD-68] Potentially fix White Screen of Death

---

.circleci/config.yml
ios/fastlane/Fastfile
package-lock.json
package.json

XCode change to 13.x necessary for new RN version (0.66). Ruby upgrade needed as a result.
React native config change: https://github.com/luggit/react-native-config/pull/609
We should figure out how we can suss out build issues like this prior to cutting release branches. It's a too late to find out that your build is going to fail.
Build via release branch
https://app.circleci.com/pipelines/github/AudiusProject/audius-mobile-client/789/workflows/8670b623-8f15-4cdb-b038-34a3df6ab8dd
*For features that are critical or could fail silently please describe the monitoring/alerting being …

Fix build issues

---

.circleci/config.yml
android/app/build.gradle
android/fastlane/Fastfile
ios/AudiusReactNative/Info.plist
ios/fastlane/Fastfile

The upgrade to react-native 0.66 broke the CI build and it wasn't caught until a release branch was cut because of the new CI setup (only building/upload release branches).
This PR:
* Configures CI to build the app on every branch
* Restricts the upload step to `release` branches
* DRYs up the ci config
* Bumps both Android and iOS to `1.1.0` for consistency

[AUD-1147] Build on every branch

---

ios/Podfile.lock
package-lock.json
package.json
src/components/web/WebApp.tsx
src/hooks/useRemoteConfig.ts
src/hooks/useSessionCount.ts
src/notifications.ts
src/services/remote-config/remote-config-instance.ts
src/store/search/hooks.ts

`@react-native-community/async-storage` has been superceded by `react-native-async-storage/async-storage` as the maintainers have changed. The upgrade was 3 minor versions to use the same version with compatibility with optimizely's sdk.
I went thru all the release notes & checked our API uses and everything should work -- no breaking changes to any of the methods we touch, and the methods look 1-1.
https://github.com/react-native-async-storage/async-storage/releases?page=4
Since this repo was a fork of the other, it uses the same storage paradigm, so we don't run the risk of losing any storage either.
*Please describe the tests that you ran to verify your changes. Provide repro instructions & …

Remove unused async storage to fix android build

---

package-lock.json
package.json
src/components/audio/Airplay.tsx
src/components/drawer/Drawer.tsx
src/components/search/TopBar.tsx
src/components/signon/CreatePassword.tsx
src/components/signon/ProfileManual.tsx
src/components/signon/SignOn.tsx
src/components/toast/ToastView.tsx

This PR upgrades `@types/react-native` to `0.66.3`. I should have done this as part of the react-native upgrade but missed it
This allows us to use `Pressable` and other v66 features
Removes the `display: none` on the AirplayViewManager because the style prop does not exist on it. I tested to make sure it does not display
Checked that there are no type errors. Tested updated components on ios simulator

[AUD-1212] Upgrade react-native types

---

src/components/top-tab-bar/TopTabBar.tsx
src/screens/ScreenHeader.tsx
src/screens/explore-screen/ExploreScreen.tsx
src/screens/explore-screen/tabs/ArtistsTab.tsx
src/screens/explore-screen/tabs/ForYouTab.tsx
src/screens/explore-screen/tabs/MoodsTab.tsx
src/screens/explore-screen/tabs/PlaylistsTab.tsx
src/screens/explore-screen/tabs/TabInfo.tsx

Adding the skeleton for the explore screen tabs and the reusable components for screens and tabs
May need to move the TabInfo component to a different location if other screens need it

Add ScreenHeader component and add skeleton for explore screen tab components

---

src/App.tsx
src/WebAppManager.tsx
src/hooks/useSelectorWeb.ts

- Adds WebAppManager to establish requirement that the web-app needs to render above native app
- Adds a check in render flow to ensure clientStore is available before rendering the rest of the native app. This simplifies `useSelectorWeb` implementation, and prevents bugs where data returned by useSelectorWeb is undefined for the first render. Weirdly enough typescript wasn't picking up the fact that `useSelectorWeb` can return undefined, so something like `const {a, b} = useSelectorWeb(someSelector)` results in a runtime error, `can't resolve a of undefined`
This change affects the root of the app, so there is a potential for things to break in weird ways.

Improve webApp render flow and missing store edge-cases

---

src/components/drawer/Drawer.tsx

Adds an (optional) `titleIcon` prop to the `Drawer` component to allow drawers to have icons in the header. Requires title to be present.
Should the `titleIcon` prop take an element or callback instead of the `ImageSourcePropType`? Thinking about SVGs here...
Locally tested using upcoming `ChallengeRewardsDrawer` changes, but with both icon included and not included.
N/A

Add optional icon to drawer title

---

src/components/button/Button.tsx

- Adds a `renderIcon` prop to the button, which accepts a callback that takes a color and returns an element
- Deprecates `icon` to encourage using the proper color for icons
- Adjusts `icon` styles to have proper margins depending on whether the icon is on the right or left
Tested manually against upcoming `ChallengeRewardsDrawer` changes, which uses both button styles and also both deprecated and new props.
N/A

Add `renderIcon` prop to button, fix margins

---

.circleci/config.yml

This PR:
* Updates CI to upload the Bounce app to testflight on pushes to `master` instead of release branches
This means that Bounce will always have latest master and we don't need to create a release branch to test features. We could potentially include release branches in the regex too, the only use case I can see for that is a hotfix on a release branch that we want to test on Bounce. Not sure if this would ever happen

Upload Bounce on master

---

src/message/index.ts
src/types/analytics.ts

Removes duplicate analytics types and uses the common ones from `audius-client`
There is a bit of funkiness required to merge the common enums with the native specific ones. One one hand it makes sense to have native specific extensions, but i can also see the argument to put them all in common. I'm up for either so lmk. Mobile also uses different naming conventions for analytics, like `Name.AnalyticsEvent` vs `EventNames.AnalyticsEvent`, and `AllEvents` vs `AllAnalyticsEvents`. happy to approach unifying those names now if it makes sense

[AUD-1278] Use common analytics types

---

src/screens/explore-screen/components/ColorTile.tsx

Interesting case where `emoji` as a React.Node means it can have falsy values like 0, which messes with styles acceptable falsy values
used `!!` here but could also do `Boolean(..)`, do we have a pref?

Fix style type for ColorTile

---

src/hooks/useIsStackOpen.ts

This PR fixes an issue where the app crashes (white/black screen) when opening a link without the app open. This happens because of a missing null check in  a piece of the new navigation logic. Although most of the navigation logic is disabled in prod, we are using a hook in notifications to determine if a stack is open. We could probably disable this via the `IS_MAIN_NAVIGATION_ENABLED` env var, but it needs to be fixed anyway and I think this is the quickest solution.
Unfortunately the type for `state.index` is number, so there was no indication that it could potentially be undefined at runtime. Might be worth adding a type declaration to override it, so we don't run into this again
Tested on …

[AUD-1293] Fix crash when opening link without app open

---

package-lock.json
package.json
src/components/theme/ThemeContext.tsx
src/hooks/useAppState.ts
src/store/sagas.ts
src/utils/logging.ts
src/utils/theme.ts

This PR:
* Fixes usage of deprecated `removeEventListener`
* Fixes deprecated forking of sagas
* Fixes warning caused by calling `useDarkMode()` too often
* Changes web app errors to log as warnings, to avoid triggering fullscreen LogBox
* Fixes react devtools in react-native-debugger by installing correct version of `react-devtools-core`
Web App errors are now being logged as warnings instead of errors! This should only have an effect when developing, as web app errors didn't crash the app to begin with
iOS simulator

[AUD-1303] Fix warnings & deprecations

---

src/components/tweet-embed/TweetEmbed.tsx

This PR wraps the request to open a url from the TweetEmbed component in a check for `canOpenURL`. This should prevent the most common log we are seeing in Sentry

[AUD-1302] Confirm that link can be opened from TweetEmbed

---

src/utils/postMessage.ts

This PR adds extra info to logging to debug this sentry log: https://sentry.io/organizations/audius/issues/2881423499/?project=1457231&query=sdk.name%3Asentry.javascript.react-native&sort=freq&statsPeriod=14d
This SO post has more details: https://stackoverflow.com/questions/47517965/howto-solve-postmessage-from-webview-to-react-native-does-not-work-for-android

[AUD-1306] Add logging around null message sender

---

package-lock.json
src/message/handlers/download.ts

QOL fix, get passed the filename instead of trying to generate it. (Filename is more important than track title, title may not exist in the case of stems)
Tested on iOS simulator, iOS Device, android Device

[AUD-1037]Get filename from client instead of generating it

---

src/components/animated-button/AnimatedButtonProvider.tsx
src/components/favorite-button/FavoriteButton.tsx
src/components/repost-button/RepostButton.tsx

This PR updates AnimatedButton to accept an optional `iconIndex` prop which allows a parent component to specify the currently active icon.
Right now, after the animation finishes the index is simply incremented. This means that if the parent state doesn't update as expected, the icon could be out of sync with the parent. It might be apply the iconIndex from props when the animation finishes

Update AnimatedButton to be controlled

---

src/components/drawer/Drawer.tsx
src/components/now-playing-drawer/ActionsBar.tsx
src/components/now-playing-drawer/AudioControls.tsx
src/components/now-playing-drawer/Logo.tsx
src/components/now-playing-drawer/NowPlayingDrawer.tsx
src/components/now-playing-drawer/PlayBar.tsx
src/components/now-playing-drawer/TrackingBar.tsx

Adds UI to now playing drawer for play bar / tracking bar (unconnected to audius-client in this PR).
The bar fades away and is replaced with an Audius logo as the drawer is swiped open.
Smaller updates:
- Animation config for now playing drawer
- Initial position / drawer height fix
- Updates drawer border opacity for parity with mobile web. Android still needs a bit of testing, probably. Using the new "Shadow" did not work with the drawer -- there might be a way to fix that.
Not in use yet
https://user-images.githubusercontent.com/2731362/150912216-e668e49d-b1dd-4a1f-aa4c-47d0260680d …

[AUD-1122] Add play bar to now playing drawer

---

src/components/button/Button.tsx

TouchableHighlight underlay is only allowed to be of type `Color | undefined`
Initially it was set to null in this PR: https://github.com/AudiusProject/audius-mobile-client/commit/9103dd3d60d3aae84ad717a7ca7d08515031f6c6
Then it was set to undefined in this PR because it was not type correct, but this caused the background to turn to black.
Ref: https://github.com/AudiusProject/audius-mobile-client/pull/224
Setting it to `transparent` does what setting it to null initially did. This affects several challenge btns and the share btn for collectibles
Fixes AUD-1388
none
Ran locally with light and dark modes

Fix Btn underlay color

---

src/components/app-navigator/AppNavigator.tsx
src/components/app-navigator/BottomTabNavigator.tsx

This PR prevents the render of disabled native screens, which will keep the useImageSizeHook error from blocking mobile release
Only affects native RN stuff
Tested on ios simulator

Prevent render of disabled native screens

---

src/styles/makeStyles.ts
src/styles/spacing.ts
src/styles/typography.ts

Style pattern that tries to unify and extend our theme use when creating styles
Usage:
```tsx
const useStyles = makeStyles(theme => ({
headerExample: {
...theme.typography.h1,
color: theme.palette.neutral
},
})
const ExampleComponent = () => {
const styles = useStyles()
return (
<Text style={styles.headerExample}>Example Header</Text>
)
}
```
Pattern draws inspiration from material-ui!
Future versions can allow props to be passed to useStyles to do more custom styling, example:
```tsx
const useStyles = makeStyles((theme, props) => ({
exampleStyle: {
color: props.something ? theme.palette.primary : theme.palette.secondary
}
})
const ExampleComponent = ({something}) => {
const styles = useStyles({something})
return (
<Text style={styles.exampleStyle}>Example Text</Text>
)
}
```
Currently, …

Add makeStyles pattern

---

src/components/card/Card.tsx
src/components/core/DynamicImage/DynamicImage.tsx
src/components/core/DynamicImage/index.ts
src/components/core/index.ts
src/components/dynamic-image/index.ts
src/components/now-playing-drawer/Artwork.tsx
src/components/now-playing-drawer/PlayBar.tsx
src/components/track-tile/TrackTileArt.tsx
src/styles/index.ts
src/styles/types.ts

- Re-routes the `style` prop to the root container
- Adds `styles` prop which includes entries for the `root`, `imageContainer`, and `image` sub elements
- Renames `image` prop to `source` to mimic the react-native Image props
- Adds `children` prop, to allow overlays
- Minor perf improvements with `useCallback`
- Moves component to "core" directory

Update DynamicImage styles, rename image to source

---

src/components/lineup/Lineup.tsx
src/components/lineup/types.ts
src/components/now-playing-drawer/Artwork.tsx
src/screens/profile-screen/EmptyTab.tsx
src/screens/profile-screen/RepostsTab.tsx
src/screens/profile-screen/TracksTab.tsx

Adds tracks and reposts tabs, leveraging the Lineup component
There was a weird bug in `Artwork.tsx` where the dominant color values where not integers and instead something like 120.0000039, which caused a rendering error for the shadow component. Added a workaround using let syntax, curious if folks like that approach vs a purely functional one

[AUD-1409] Add profile-page tracks and reposts tabs

---

src/components/card/Card.tsx
src/components/collection-list/CollectionList.tsx
src/components/core/CardList.tsx
src/components/core/Tile.tsx
src/screens/explore-screen/tabs/ArtistsTab.tsx
src/screens/feed-screen/FeedScreen.tsx

- Refactors Card component to use Tile
- Simplifies CardList impl since we wrap a View now instead of passing style through to card. This is needed cause padding directly on the card Tile messes with shadow.
- Updates tile shadow to more closely align with web client tile shadows

Refactor Card to use Tile, update Tile shadows

---

src/components/notifications/content/ChallengeReward.tsx
src/store/notifications/types.ts

Adds notification config for `ref-v` or verified referrals challenge
Tested using proxy

Add notification config for referrals-verified

---

src/components/core/DynamicImage/DynamicImage.tsx

Adds `onLoad` prop to know when the dynamic image has finished transitioning images
Fixes `children` prop by wrapping it in a relative view, which helps with absolute positioning overlays

Add onLoad prop and children fix to DynamicImage
