src/components/notification-reminder/NotificationReminder.tsx, src/components/web/WebApp.tsx, src/message.ts, src/utils/postMessage.ts, src/utils/useSessionCount.ts
- Need to handle WebApp prompting native layer to present the push notification reminder
- Also refactor handleMessage so we don't have to carpetbomb JSON.stringify everywhere
- Adds logging
=> Handle prompt to enable push notifications

ios/AudiusReactNative.xcodeproj/project.pbxproj, ios/AudiusReactNative/Info.plist, ios/Podfile.lock, package-lock.json, package.json, src/components/web/WebApp.tsx, src/utils/logging.ts, src/utils/theme.ts
See: https://github.com/AudiusProject/audius-client/pull/194
Additionally, I now have the StatusBar invisible now during iOS splashscreen (since we don't necessarily know the correct color then, and the splash screen looks better without a StatusBar).
=> Fix StatusBar colors

src/message.ts
Not entirely clear how this got excluded from the original PR...
=> Listen to Theme Change messages

android/app/build.gradle, ios/AudiusReactNative.xcodeproj/project.pbxproj, ios/AudiusReactNative/Info.plist
=> Bump versions

src/components/header/Header.tsx, src/components/image/ImageLoader.tsx, src/components/image/PlaylistImage.tsx, src/components/image/TrackImage.tsx, src/components/image/UserImage.tsx, src/components/image/utils.ts, src/components/search/Search.tsx, src/components/search/SearchHistory.tsx, src/components/search/SearchResults.tsx, src/components/search/TopBar.tsx, src/components/search/content/EmptySearch.tsx, src/components/search/content/MoreContainer.tsx, src/components/search/content/SearchItem.tsx, src/components/search/content/SearchSectionHeader.tsx
* adds correct font
* Fixes the text gradient
* Fades in images
* Adds legacy load image on failure
Also relies on changes from https://github.com/AudiusProject/audius-client/pull/397
=> Minor fixes for native search

src/components/header/Header.tsx, src/components/search/SearchHistory.tsx, src/store/search/hooks.ts, src/store/search/reducer.ts
* Fix text shadow on the header
* Prevent the updated search text from appearing in history before the results appear
=> Search edits

android/app/build.gradle, ios/AudiusReactNative.xcodeproj/project.pbxproj, ios/AudiusReactNative/Info.plist
Includes:
* Fix for TikTok CSRF cookie
=> Bump builds

.env.dev.tmpl, .env.prod.tmpl, src/components/oauth/OAuth.tsx
This PR:
* Adds the fetching of the TikTok access token into the injected oauth webview logic. Previously, the required csrf cookie did not persist on ios
Need to make sure that the `IDENTITY_SERVCE` env var is set properly in the build
Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.
For features that are critical or could fail silently please describe the monitoring/alerting being added.
=> Fix TikTok CSRF Cookie

src/components/oauth/OAuth.tsx
This PR updates the tiktok auth logic to pass any errors back to the web layer to be recorded via analytics
=> Pass tik tok auth errors to web layer

.github/pull_request_template.md, README.md, ios/AudiusReactNative.xcodeproj/project.pbxproj, ios/Podfile, ios/Podfile.lock, package-lock.json, package.json
Makes it so we don't have to do any extra work on M1 to get the iOS simulator working. (esp between pod installs)
On M1, you should do 
```
brew install ruby
sudo gem install cocoapods
```
so pod install works
Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?
Some package version upgrades. Will want to look closely, but just coming from a `Pod update`
Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.
Tested on M1 and intel-based
For features that are critical or could fail silently please describe the monitoring/alerting being added.
=> Update readme and firebase deps

src/components/notifications/NotificationBlock.tsx, src/components/notifications/content/ChallengeReward.tsx, src/components/notifications/content/NotificationContent.tsx, src/components/notifications/content/TwitterShare.tsx, src/components/notifications/routeUtil.ts, src/store/notifications/types.ts, src/utils/routes.tsx
Added code to display notifications for challenge rewards
Tested in mobile emulator
=> Add notifications for challenge rewards

src/components/notifications/NotificationBlock.tsx, src/components/notifications/content/NotificationContent.tsx, src/components/notifications/content/TierChange.tsx, src/components/notifications/content/TwitterShare.tsx, src/components/notifications/routeUtil.ts, src/store/notifications/types.ts, src/utils/routes.tsx
Adding mobile notifications for $AUDIO Tier Changes
Manually tested with iOS emulator
=> Add notifications for  tier changes

android/app/build.gradle, ios/AudiusReactNative.xcodeproj/project.pbxproj, ios/AudiusReactNative/Info.plist
Bumps the patch version for ios and android
None
=> Version patch

ios/Podfile.lock, package-lock.json, src/components/signon/CreatePassword.tsx, src/components/signon/ProfileImage.tsx, src/components/signon/ProfileManual.tsx, src/components/signon/SignOn.tsx
- behavior on the password check marks same as web
- Fix touch targets on "sign in/up switcher"
- spinner on the image after uploading photo (although it's super brief and sometimes not there because phot immediately available). also fade in
- add some easing to the slide-in animation that plays when the sign-up flow opens. also add top margin above logo
Manual spin up of iOS and Android emulators
=> Fix style issues and discrepancies

src/App.tsx
Realized I had dropped an export with the notifications work. Typescript was complaining but the because the build doesn't fail I missed it
=> Fix dropped dispatch export

package-lock.json, package.json
Include commit sha to dependency so that CI will not used cached version of dependencies when there is a new release.
=> Update audius-client dependency

android/app/build.gradle
=> Bump android version

.circleci/config.yml, package-lock.json, package.json
Update audius-client SHA to working version with models/Analytics
=> Update audius-client SHA

package.json
=> Update client module commit hash

README.md
=> Adds notes to readme about using XCode to debug

package-lock.json, package.json, src/App.tsx, src/components/transfer-audio-mobile-drawer/TransferAudioMobileDrawer.tsx, src/components/transfer-audio-mobile-drawer/index.ts
Add native mobile transfer audio drawer
Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?
Locally against native mobile app on iOS
For features that are critical or could fail silently please describe the monitoring/alerting being added.
=> Add native mobile transfer audio drawer

android/app/build.gradle
Bump android build due to CI breakage
Unclear whether Kotlin build issues are attributed: 
https://app.circleci.com/pipelines/github/AudiusProject/audius-mobile-client/640/workflows/4647c975-52af-41ed-ad7a-07fc308d03ab
=> Bump android build due to CI breakage

package-lock.json, package.json
=> Bump client hash

src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
Open share sheet on audio breakdown drawer wallet copy click
iOS locally
=> Open share sheet on audio breakdown drawer wallet copy click

.env.prod.tmpl, .env.stage.tmpl
Use dummy values for stage and prod analytics for local dev
=> Use stage/prod amplitude dummy values

src/App.tsx, src/components/connect-wallets-drawer/ConnectWalletsDrawer.tsx, src/components/connect-wallets-drawer/index.ts
Add connect wallets drawer
Manually tested. It looks great
=> [AUD-1011] Add connect wallets drawer

src/components/connect-wallets-drawer/ConnectWalletsDrawer.tsx
Updated font-weight css style to weight prop to have consistent styles on Android
Manually checked. looks the same
=> Update font-weight css style to weight prop

package.json
Update client hash to reflect changes in https://github.com/AudiusProject/audius-client/commit/76947480afa2dea1abe0ce04a969d4088f2ff193
Tested in https://github.com/AudiusProject/audius-client/commit/76947480afa2dea1abe0ce04a969d4088f2ff193
=> Update hash for download tracks

package.json
=> Update client version

.circleci/config.yml, ios/AudiusReactNative.xcodeproj/project.pbxproj
https://app.circleci.com/pipelines/github/AudiusProject/audius-mobile-client/844/workflows/920e1a9f-c7b8-4bab-9071-e08fee90866f
https://github.com/getsentry/sentry-cli/issues/1015#issuecomment-997314459
😓 
CI
=> Fix sentry-cli by installing in CI

package.json
=> Remove console.time

src/components/api-rewards-drawer/ApiRewardsDrawer.tsx
=> Fix type/lint issues

.circleci/config.yml, ios/AudiusReactNative.xcodeproj/project.pbxproj, ios/Podfile, ios/scripts/bundleReactNative.sh, ios/scripts/uploadSentryDebugSymbols.sh
Fixes setup & CI
* Remove unnecessarily linked RN fetch blob
* Remove npm upgrade in CI (version clashing issue b/w mobile & client, and generally bad practice. Also sent this change to audius-client repo)
* Move startup scripts to use $SENTRY_BINARY if set
Builds
=> Fix setup and CI

package-lock.json, package.json
Bumps client build to include hidden tracks on profile page
=> Bump client to support hidden tracks

src/types/analytics.ts
Rename the page view event type to be consistent with web
=> Fix casing for page view event name

src/components/dynamic-image/DynamicImage.tsx, src/components/dynamic-image/index.ts
This PR adds the `DynamicImage` component
Tested transitioning between images & placeholders on ios simulator
=> [AUD-1194] DynamicImage

package-lock.json, package.json
See https://github.com/AudiusProject/audius-protocol/pull/2220
=> Update client to flare-51 fixes (404 safeguarding)

package-lock.json, package.json
Updates the audius client dependency hash to latest master
This was tested against staging to check that user bank creation happened on signup and profile completed were working on mobile. 
ran against staging
=> Update audius client dep hash

src/components/notifications/content/ChallengeReward.tsx
=> Fix rewards amounts

package-lock.json, package.json, src/components/share-drawer/ShareDrawer.tsx, src/components/share-drawer/messages.ts, src/components/share-drawer/utils.ts
Uses the new share-modal state, which enables sharing artists, tracks, and collections.
=> [AUD-1273] consume new share state, handle collections

src/components/share-drawer/ShareDrawer.tsx
- Fixes TikTok action styles for matrix mode
- Fixes toast content to display contentType
=> Fix matrix-mode styles, toast content

package-lock.json, package.json
=> Consume latest challenges UI

package-lock.json, package.json, src/components/notifications/List.tsx, src/components/notifications/NotificationBlock.tsx
Adds react-native-shadow-2 to improve shadow consistency across android and ios. Ultimately, the goal was to keep android shadows similar, and improve android shadows.
iOS before:
iOS after: 
Android Before: 
Android After: 
The main question was performance. After adding it to the notifications panel which has a lot of items, i didn't notice any scroll performance or load time issues, esp on an old device. Methods were imprecise, however
=> [AUD-1276] Add shadow library, apply to NotificationBlock

package-lock.json, package.json
Fixes issues with History and react-router-dom
=> Upgrade client to fix type issues

package-lock.json, package.json, src/App.tsx, src/components/edit-collectibles-drawer/EditCollectiblesDrawer.tsx, src/components/edit-collectibles-drawer/index.ts
[AUD-1025]
Adding EditCollectiblesDrawer component. Manually tested, looks like a drawer 👁️ 👁️
=> [AUD-1025] Add EditCollectiblesDrawer component

src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx, src/components/button/Button.tsx, src/components/challenge-rewards-drawer/ReferralLinkCopyButton.tsx, src/components/icon-button/IconButton.tsx, src/components/signon/FirstFollows.tsx, src/hooks/usePressScaleAnimation.ts
Adds a new generic hook `usePressScaleAnimation` to replace existing animation sequences for buttons
Tested a settings button and my copy button from #213 on iOS simulator
N/A
=> Use hook for press scale animation on buttons

.circleci/config.yml
Switch to npm ci instead of install in circle to get deterministic builds
=> Npm install => npm ci

src/components/card/Card.tsx, src/components/card/index.ts, src/components/dynamic-image/DynamicImage.tsx, src/screens/explore-screen/components/ArtistCard.tsx, src/screens/explore-screen/components/CollectionCard.tsx, src/screens/explore-screen/tabs/ArtistsTab.tsx, src/screens/explore-screen/tabs/PlaylistsTab.tsx
[AUD-1234]
* Add Card Component for rendering out explore tiles
* Add ArtistCard and CollectionCard components
* Update DynamicImage component to resize the internal image
* Are there any issues with the resize logic being added to DynamicImage?
Manually tested with test data. Another PR will be added soon to update the store in audius-client and have ArtistsTab and PlaylistsTab consume data from the store
=> [AUD-1234] Add Card component

src/components/share-drawer/utils.ts
Fixes issue where copying artist link results in relative url
=> Fix copy artist link

package-lock.json, package.json, src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx, src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
Upgrades redux-saga and uses upgraded audius-client
There are relatively few native sagas, so any errors i suspect will come from audius-client
=> Upgrade redux-saga from 0.16.2 to 1.1.3

src/components/drawer/Drawer.tsx
Fix drawer radius bug on overscroll.
Simulator
- share drawer
- overflow drawer
- upload track drawer
- now playing drawer
- collectible details drawer
=> [AUD-1381] Fix drawer border 0 bug

src/components/now-playing-drawer/NowPlayingDrawer.tsx, src/components/now-playing-drawer/PlayBar.tsx, src/components/now-playing-drawer/TrackingBar.tsx
Connect now playing bar to store (RN & web).
Blocked:
- Controlled button component
- Redux context <Provider> issue
Locally vs. staging
=> [AUD-1122] Connect play bar

package-lock.json, package.json, src/screens/profile-screen/CoverPhoto.tsx, src/screens/profile-screen/ExpandableBio.tsx, src/screens/profile-screen/ProfileBadge.tsx, src/screens/profile-screen/ProfileMetrics.tsx, src/screens/profile-screen/ProfilePhoto.tsx, src/screens/profile-screen/ProfileScreen.tsx, src/screens/profile-screen/ProfileSocials.tsx, src/screens/profile-screen/Sites.tsx
Updates profile imports to use common profile store
=> [AUD-1439] Use common profile store

src/hooks/useCollectionCoverArt.ts, src/hooks/useTrackCoverArt.ts, src/hooks/useUserCoverPhoto.ts, src/hooks/useUserProfilePicture.ts
Did a whoops. Fixing the whoops.
Image hooks for mobile now pass useDispatchWeb so that the fetch actions will actually fetch the art
The images now render 👍
=> Update image hooks to use dispatchweb

src/screens/profile-screen/AlbumsTab.tsx, src/screens/profile-screen/CollectionList.tsx, src/screens/profile-screen/PlaylistsTab.tsx, src/screens/profile-screen/ProfileTabNavigator.tsx
Adds playlists and albums profile tab using FlatList. Will follow up with a refactor to include explore page lists.
=> [AUD-1410] Add playlists and albums profile tab

src/components/track-tile/TrackTile.tsx, src/hooks/useNavigation.ts
First pass at merging native and web navigation into a single hook. Maintains strong typing for native navigation, and we can work on a similar strong typing for web too.
=> [AUD-1464] Merge native and mobile navigation

src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx, src/components/notifications/content/ChallengeReward.tsx
Update track upload count
Note should be sent over from client in the future
=> Update upload track count

src/components/app-navigator/BottomTabNavigator.tsx, src/components/app-navigator/TopBar.tsx, src/components/search/content/SearchItem.tsx, src/screens/explore-screen/components/ArtistCard.tsx
Small pr to open profile screen from artist card.
=> [AUD-1457] Open profile page from track tile and artist card

package-lock.json, package.json, src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx, src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx, src/components/challenge-rewards-drawer/ReferralLinkCopyButton.tsx, src/components/challenge-rewards-drawer/TwitterShareButton.tsx
[AUD-1479](https://linear.app/audius/issue/AUD-1479/mobile-aggregate-challenges-ui)
See also: https://github.com/AudiusProject/audius-client/pull/876
- Hides progress bar for aggregate challenges
- Shows text for claimable and claimed challenge amounts
- Updates error message
- Updates claim action to use list of specifiers
UPDATED:
~~That last screenshot looks pretty close to the bottom of the phone. Is the drawer scrollable?~~
Locally against iOS simulator
N/A
=> [AUD-1479] Add support for aggregate challenges to the rewards drawer

src/App.tsx, src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx, src/components/add-to-playlist-drawer/index.ts, src/components/card/Card.tsx, src/components/core/CardList.tsx
Added Add to Playlist drawer component
Manually tested. There is one small weirdness with scrolling the first time that I can't quite figure out, but everything else works
=> Add AddToPlaylistDrawer

package-lock.json, package.json, src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
- Use claimableAmount instead of undisbursedAmount, as it's more accurate and clear
- Remove progress bar on challenges with only 1 step
=> Consume latest client for challenges changes
